### ISSUE TITLE
App is being crash while SDK configuration 

### ISSUE THREAD

**Issue by deepaksharma010** [ShipBook/ShipBookSDK-iOS#1]
App is crashing on this line ShipBook.start(appId: "APP_ID", appKey: "APP_KEY")
Reason - force unwapping in identifierForVendor
 Line 42: udid = UIDevice.current.identifierForVendor!.uuidString in Login.swift file

**Comment by elishas** [comment]
Can you tell me what device it is? How can I reproduce the situation?

**Comment by deepaksharma010** [comment]
I tried but won’t able to reproduce this as it is happening randomly. But crashlytics shows, app is crashing when we try to save uuid in Login.swift class

**Comment by elishas** [comment]
We will investigate it. We didn't have any other complaints about it. We will try to come back with a solution at the start of next week.

**Comment by elishas** [comment]
a new version came out with the fix
