### ISSUE TITLE
Missing user information in log session in background

### ISSUE THREAD

**Issue by gDeep1** [ShipBook/ShipBookSDK-iOS#10]
I have been looking for the answer to following scenario but did not get any. So I am posting it here. I have integrated Shipbook logs in my application which track user location in background. 

I set up the Shipbook in app delegate and register user after it. It works fine after that. But sometimes, the session does not include the user id and name when i look into the logs in Shopbook logbook. It miss user information for few session/s and has same UUID only. Mostly it is the case of tracking logs in background when a significant location change happens. App is not in foreground at that time. 

What could be the potential reason for that?

**Comment by elishas** [comment]
Based on your description, it appears that a new session may be created while the app is in the background, and the app does not call the **registerUser** API. Consequently, no user is registered for this session. The SDK does not retain user information from one session to the next. Therefore, it is the developer's responsibility to provide this information via the **registerUser** API.
