### ISSUE TITLE
New version of Shipbook is preventing app to be uploaded to TestFlight

### ISSUE THREAD

**Issue by tiagoribeiro4** [ShipBook/ShipBookSDK-iOS#2]
As the title indicates, there is an issue with the most recent versions when uploading to Testflight.
It looks to be related with recently added file `shipbook_build_dsym_upload.sh`.

The full error from TestFlight is 

> [Transporter Error Output]: ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [app_name.app/Frameworks/ShipBookSDK.framework/shipbook_build_dsym_upload.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

Reverting ShipBook version to 1.1.10 fixes the problem in the mean time.

**Comment by elishas** [comment]
Thanks, for reporting the issue. We are the whole time trying to improve. We fixed the issue.

**Comment by axelpart** [comment]
Hello @elishas. We faced the same issue recently using the ShipbookSDK through Carthage. I can see that the provided fix is available through CocoaPods integration. Do you know if there is a plan to provide a fix for Carthage?

**Comment by elishas** [comment]
did you download version 1.1.17 in carthage. The issue is supposed to be fixed there.

**Comment by axelpart** [comment]
> did you download version 1.1.17 in carthage. The issue is supposed to be fixed there.

Yes, we observed the issue with version 1.1.17 using Carthage.

**Comment by elishas** [comment]
We deleted the problematic file and the next build will surely work also on
carthage
