### ISSUE TITLE
App is being crashed because of timer in SBCloudAppender class

### ISSUE THREAD

**Issue by deepaksharma010** [ShipBook/ShipBookSDK-iOS#3]
My app is facing three crashes which are related to timer. We are using version 1.1.8
1. 
<img width="971" alt="Screenshot 2020-07-15 at 5 03 05 PM" src="https://user-images.githubusercontent.com/55547153/87561554-23cd5800-c6bd-11ea-9f7f-00275af0bc6e.png">

2. 
<img width="726" alt="Screenshot 2020-07-15 at 5 02 46 PM" src="https://user-images.githubusercontent.com/55547153/87561577-292aa280-c6bd-11ea-87b3-dab718057a48.png">

3.
<img width="801" alt="Screenshot 2020-07-15 at 5 02 33 PM" src="https://user-images.githubusercontent.com/55547153/87561645-40699000-c6bd-11ea-8985-a0eadc084097.png">

**Comment by elishas** [comment]
We are trying to understand the cause of these crashes. 
Can you give me more information like the number of times that it happened?
Does it still happen?
Is it happening with all devices? all os?

**Comment by deepaksharma010** [comment]
This is still happening for all devices to many user. 
<img width="1218" alt="Screenshot 2020-07-24 at 11 28 47 PM" src="https://user-images.githubusercontent.com/55547153/88436990-c98f6e00-ce05-11ea-8457-5c05d1d687d1.png">

I am not sure but It seems something wrong is happing with timer when app is in background. I found a good article about this, might help to you.

https://medium.com/over-engineering/a-background-repeating-timer-in-swift-412cecfd2ef9

**Comment by elishas** [comment]
We believe that we fixed the issue. ( We can never be sure due to the fact that we don't succeed to reproduce the issue.)
Please update the version to 1.1.14 

Please tell me if it fixed it.
