### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by ghost** [ShipBook/ShipBookSDK-iOS#5]
Hi guys.
Thanks for your product. Currently I use SwiftyBeaver, but it looks that your product also supports collect crashes. If so it will be great and I wanna to switch on it.
The main question - can you add swift package manager support?

Thanks

**Comment by elishas** [comment]
We are in the midst of adding package manager support. We expect to have it added in around two weeks.

**Comment by ghost** [comment]
Thanks for update. Two notes:
1) it does not work by adding SPM via tags - XCode can't find package manifest for current tag version. If I select master, everything is ok
2) =================== 15:26:09.463 Error save to file error: Folder «CloudQueue.log» does not exists.

**Comment by elishas** [comment]
We still didn't finish the development on this feature. That is why we didn't give it a new tag. This version doesn't send logs to the server. 
Only when we will close the issue you'll be able to use it. I hope in the next few days. The transfer to SPM was difficulter than what we expected.

**Comment by elishas** [comment]
It is now working on version 1.1.16
Please update me that it now works OK
