### ISSUE TITLE
Memory Leak as soon as SDK is started

### ISSUE THREAD

**Issue by farrukhaskari1** [ShipBook/ShipBookSDK-iOS#7]
<img width="610" alt="Screenshot 2022-08-21 at 4 10 13 PM" src="https://user-images.githubusercontent.com/6830947/185788256-274d319d-38e9-44e5-8016-7e03d6d0b861.png">
memory starts leaking as soon as ShipBook SDK is started. What can possibly be causing it?

**Comment by farrukhaskari1** [comment]
I am using Firebase. so If you have Remote Config enabled, the Firebase Performance comes bundled with it and is ON by default. The workaround is to turn OFF Firebase Performance.

Performance.sharedInstance().isDataCollectionEnabled = false
Performance.sharedInstance().isInstrumentationEnabled = false

**Comment by elishas** [comment]
The issue was fixed. It would be great if @askari01 could download the last version and check that it is now OK

**Comment by farrukhaskari1** [comment]
I will test this week and update accordingly.

**Comment by farrukhaskari1** [comment]
no more memory leaks, thanks
